### ISSUE TITLE
Grape vine block model showing white background

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.19#23]
Need to review all of the grape vine and hops block models.

**Comment by CastorF1ber** [comment]
![Jdk-19 Screenshot 2023 04 16 - 19 20 58 70](https://user-images.githubusercontent.com/85393018/232329665-e4791b9e-8048-409a-901d-01d2c191084d.png)
This bug happens only on the first stage of growing (when it is small and lower than 1 block high). On the other stages everyhing is okay.
